### ISSUE TITLE
Website update for ODD 2024

### ISSUE THREAD

**Issue by lucpretti** [okfn/opendataday#388]
We need to make some cosmetic changes to better align ODD's visual identity with OKFN's new brand guidelines. As well as adding some specific sections for 2024.

The main features (map, event registration, internal pages) won't be changed.

Here's how the website should look like (assets and texts below):

![ODD-2024-website-v2](https://github.com/okfn/opendataday/assets/8523847/ebbc1a50-2c35-4548-9c88-47c3538c3109)

**Tasks:**

- [ ] Replace font-family with HK Grotesk (respecting the different weights):
Files available here: https://drive.google.com/file/d/11ffEezgjG3WeRdkk_0gMW71PpjdztVw0/view?usp=sharing

- [ ] Update all texts font-color to black `#000` (keep white in the menu only)

- [ ] Add OKFN collapsable panel as a top header
(The same updated version displayed on sites like [opendefinition.org](https://opendefinition.org) and [opendatacommons.org](https://opendatacommons.org))

- [ ] Update footer also following the pattern on [opendatacommons.org](https://opendatacommons.org)) (but adding a line of text and licencing specific to ODD)

- [ ] Update favicon to:
https://drive.google.com/drive/folders/1yCP1HSKTysUsWFVHTbrPQMPCLfmMu-X2?usp=sharing

- [ ] Replace colors on the map
`#ff4900` to `#e077ff`
`#0186ff` to `#00d1ff`
`#ffb901` to `#e4ff36`

Please Implement the changes according to the design file above, using the following resources. I'm not sure if it's helpful, but we're reusing some of the components already developed for okfn.org - you can find the frontend code [here](https://ishigami.github.io/okfn_front/components) and [here](https://ishigami.github.io/okfn_front/components-2.html). 

I know there are some elements missing (mostly links), but I'll add them later once the design changes are implemented.

---

**Assets:**

- Top banner: https://drive.google.com/file/d/1-AdkO7Ax-_l1Iu1RyOwb2OKSzcPXoSti/view?usp=sharing

- Logo ODD white: https://drive.google.com/file/d/1z52T-N6gT3dvvpdnXMWq9fOF3UT3fFza/view?usp=sharing

- Logo OKFN white: https://drive.google.com/open?id=1ZE8Zh0vGC78_cZG1jPP1z6q1DxA99rIz&usp=drive_fs

- Hands illustration: https://drive.google.com/open?id=1-xTiGYiy07lW-ciCMb_ZyiHRoOrfx-zo&usp=drive_fs

---

**Texts:**

Join. Host. Support.
Celebrate Open Data
Where You Are

Save the Dates!
March 2-8, 2024

Open Data Day (ODD) is an annual celebration of open data all over the world. Groups from likely every country create local events on the day where they will use open data in their communities. ODD is led by the [Open Knowledge Foundation](https://okfn.org) (OKFN) and this year’s edition is co-organised by members of the [Open Knowledge Network](https://okfn.org/en/network). 

As a way to increase the representation of different cultures, since 2023 we offer the opportunity for organisations to host an Open Data Day event on the best date between March 2nd and 8th.

All outputs are open for everyone to use and re-use.

Thematic Focus: Open Data for Advancing  Sustainable Development Goals (SDGs)

Following CKAN's recognition as a digital public good, in 2024 we will explore how open data is a key player in helping to achieve the UN’s Sustainable Development Goals (SDGs).

Learn more _(link missing)_

button: Register your event _(link missing)_
button: [Join the community](https://groups.google.com/forum/#!forum/open-data-day)

Open Data Day is for everyone!

If you have an idea for using open data, want to find an interesting project to contribute towards, learn about how to visualise or analyse data or simply want to see what's happening, then come participate! 

Participation is a core value of Open Data Day, everyone is free to voice their opinions in a constructive manner. No matter your skill-set or interests, we are encouraging organisers to foster opportunities for you to learn and help the global open data community grow.

People
We need you the most. If it wasn’t for you, this whole thing wouldn’t be happening. Wherever you come from and whatever your background, we need you.

Public servants
Your input and context can help us to make government data better. Come converse and learn.

Designers
Help us make open data relatable, so more people will use it and understand it.

Developers
Use your skills to develop solutions that can help solve important societal issues.

Statisticians
Use your skills to help understand the data and get important insights from it.

Event Resources

Need some inspiration for an Open Data Day event, or don't know where to find the data you need? Check out our event resources.

button: [Resources](https://opendataday.org/#resources)

Become a Sponsor

We believe that working in partnership is the key to maximising our impact. The Open Knowledge Foundation is looking for partners to support Open Data Day in 2024. Find out the sponsorship tiers and consider joining us in the world’s largest and more important celebration of open data. For more information, please contact carolina.matos@okfn.org.

button: Sponsorship Pack _(link missing)_

[Privacy policy](https://okfn.org/privacy-policy/)
[IP policy](https://okfn.org/ip-policy/)
[Cookie policy](https://okfn.org/cookie-policy/)
[Terms of use](https://okfn.org/terms-of-use/)

The Open Knowledge Foundation is a not-for-profit organisation. It is incorporated in England & Wales as a company limited by guarantee, with company number 05133759. VAT Registration № GB 984404989. Registered office address: Open Knowledge Foundation, 86-90 Paul Street, London, EC2A 4NE, United Kingdom.

This is a bottom-up initiative. Open Knowledge helps organise and maintain it to foster a community. Everyone can contribute. 

Licence Information:
The Open Data Day website code and text content are made available under the CC0 1.0 licence
Event Data files are made available under the Open Database License
This site uses icons from icomoon under the CC BY 4.0 licence

**Comment by tuukka** [comment]
Did you consider an update to the colors of the map too?

**Comment by lucpretti** [comment]
> Did you consider an update to the colors of the map too?

Great point @tuukka, thank you – I'll add it to the issue.
